export const materialsContent = [{
  id: '1',
  type: 'article',
  url: 'https://drive.google.com/file/d/1v9c-ae576adMYFeNl0Wz1LmQUQhvm8cC/view?usp=drive_link',
  thumbnail: '',
  title: 'Ambientalismo e educação ambiental: dos discursos às práticas sociais',
  description: '',
  authorNames: ['Andréa Focesi Pelicion'],
}, {
  id: '2',
  type: 'article',
  url: 'https://drive.google.com/file/d/1xR6bRljzvaZ3tsKb_b200eFmbsFmK7DW/view?usp=drive_link',
  thumbnail: '',
  title: 'Valorização dos saberes ambientais ribeirinhos e a relação com a produção sustentável de alimento no processo de formação escolar',
  description: '',
  authorNames: ['Carmélia do Socorro Siqueira Cardoso'],
}, {
  id: '3',
  type: 'article',
  url: 'https://drive.google.com/file/d/1-0goFk0qzSIXG855YsdCX4Eee-fz4Zvb/view?usp=drive_link',
  thumbnail: '',
  title: 'Desenvolvimento e aplicação de atividade de Educação Ambiental: lagartixa das dunas (Liolaemus arambarensis) em foco',
  description: '',
  authorNames: ['Rafaela Grego', 'Artur Antunes Navarro Valgas', 'Tatiane Alves Gonçalves', 'Laura Verrastro'],
}, {
  id: '4',
  type: 'article',
  url: 'https://drive.google.com/file/d/1QSagbjqjHsfBwmO7hIG9cLY67hrZskMS/view?usp=drive_link',
  thumbnail: '',
  title: 'Educação ambiental na era digital: NASA’s Climate Kids como recurso didático para o ensino sobre mudanças climáticas.',
  description: '',
  authorNames: ['Railson de Jesus Diniz.'],
},
{
  id: '5',
  type: 'article',
  url: 'https://drive.google.com/file/d/1HZ9DNnq-Z_MN49ey-by-i7jOliuo7noV/view?usp=drive_link',
  thumbnail: '',
  title: 'Horta escolar como proposta de metodologia ativa na Educação Ambiental: um relato de experiência em uma escola estadual de São Carlos (São Paulo)',
  description: '',
  authorNames: ['Marcelo Damiano', 'Rafaela Bruno Ichiba', 'Maria Olímpia de Oliveira Rezende'],
},
{
  id: '6',
  type: 'article',
  url: 'https://drive.google.com/file/d/1nHG4dcS1Jk3djNemLEhS8Qs_A7rOHO-a/view?usp=drive_link',
  thumbnail: '',
  title: 'Utilização de animações como metodologia ativa para o ensino da Educação Ambiental',
  description: '',
  authorNames: ['Damiao Sampaio de Sousa', 'Amanda Stefani Ferreira Meneses', 'Francisco Rogênio da Silva Mendes', 'Márcia Machado Marinho', 'Sandro Olímpio Silva Vasconcelos', 'Emmanuel Silva Marinho'],
},
{
  id: '7',
  type: 'article',
  url: 'https://drive.google.com/file/d/1nf98h4xTLJoICn-ykV4Ql2el86dI0CEx/view?usp=drive_link',
  thumbnail: '',
  title: 'METODOLOGIA PARA CRIAÇÃO DE JOGOS A SEREM UTILIZADOS NA ÁREA DE EDUCAÇÃO AMBIENTAL',
  description: '',
  authorNames: ['IVANA THEREZINHA GOGOLEVSKY KOSLOSKY'],
},
{
  id: '8',
  type: 'article',
  url: 'https://drive.google.com/file/d/1KZlf6tNyFI_2MpKBOKjcOX2H-ctybpgL/view?usp=drive_link',
  thumbnail: '',
  title: 'A Educação Ambiental na formação de professores',
  description: '',
  authorNames: ['Juliana Marques Costa', 'Paulo Tadeu Campos Lopes'],
},
{
  id: '9',
  type: 'article',
  url: 'https://drive.google.com/file/d/1_fvwOvhcb1vcuC1LvwAWeVI_OKjqmvdp/view?usp=drive_link',
  thumbnail: '',
  title: 'A consolidação do movimento ambientalista e da educação ambiental no Brasil e no mundo: algumas perspectivas históricas',
  description: '',
  authorNames: ['Neimar Afonso Sornberger'],
},
{
  id: '10',
  type: 'article',
  url: 'https://drive.google.com/file/d/1bL391hmT-qhamSYvTOLtw3thpk10w6Ht/view?usp=drive_link',
  thumbnail: '',
  title: 'Educação ambiental como política pública',
  description: '',
  authorNames: ['Marcos Sorrentino'],
},
{
  id: '11',
  type: 'article',
  url: 'https://drive.google.com/file/d/1Gw9EVrMLFYMtEbavJFDk40QDrvUBxqmk/view?usp=drive_link',
  thumbnail: '',
  title: 'PENSANDO E PRATICANDO a Educação Ambiental na Gestão do Meio Ambiente',
  description: '',
  authorNames: ['Org. José Silva Quintas'],
},
{
  id: '12',
  type: 'article',
  url: 'https://drive.google.com/file/d/1ojo65DH_tAyyH0MDmKMAQfNR4tPHoiNl/view?usp=drive_link',
  thumbnail: '',
  title: 'Identidades da Educação Ambiental Brasileira',
  description: '',
  authorNames: ['Philippe Pomier Layrargues'],
},
];