export const materialsContent = [{
  id: '1',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 1',
  description: 'Description 1',
  authorNames: ['Author 1', 'Author 2'],
}, {
  id: '2',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 2',
  description: 'Description 2',
  authorNames: ['Author 3', 'Author 4'],
}, {
  id: '3',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 3',
  description: 'Description 3',
  authorNames: ['Author 5', 'Author 6'],
}, {
  id: '4',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 4',
  description: 'Description 4',
  authorNames: ['Author 7', 'Author 8'],
}, {
  id: '5',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 5',
  description: 'Description 5',
  authorNames: ['Author 9', 'Author 10'],
}];