export const materialsContent = [{
  id: '1',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 1',
  description: 'Description 1',
}, {
  id: '2',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 2',
  description: 'Description 2',
}, {
  id: '3',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 3',
  description: 'Description 3',
}, {
  id: '4',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 4',
  description: 'Description 4',
}, {
  id: '5',
  type: 'video',
  url: 'https://www.youtube.com/watch?v=h8-qemIbXbo',
  thumbnail: 'https://i.ytimg.com/vi/h8-qemIbXbo/maxresdefault.jpg',
  title: 'Video 5',
  description: 'Description 5',
}];